Refactor/extract common class
haimkastner/unitsnet-py pull request #11
Opened 2023-08-23 03:28 UTC by ivanovmg

Extract class with common comparison operators.
Closes #10  

Note that I had to use ``_value`` instead of ``__value``, since double underscore variable is not accessible from sibling classes.
In addition, I used ``total_ordering`` to avoid duplication of comparison methods.
And finally, I made use ``NotImplemented`` to delegate comparison to other class if the current one cannot handle it. This is considered a common practice in Python.

2023-08-26 18:22 UTC, haimkastner requested changes

2023-08-26 18:22 UTC, haimkastner commented on unitsnet_py/abstract_unit.py
> +    def __lt__(self, other: AbstractMeasure):
The `__et__`, `__le__`, and `__ge__` are not missing?

2023-08-26 18:22 UTC, haimkastner commented on unitsnet_py/abstract_unit.py
> +            return NotImplemented
It should not be a `raise TypeError("unsupported operand....` ?

2023-08-28 02:08 UTC, ivanovmg commented on unitsnet_py/abstract_unit.py
> +    def __lt__(self, other: AbstractMeasure):
No, this is a magic of ``@total_ordering`` decorator.
It is necessary to define only ``__lt__`` and ``__eq__``, while other methods are created under the hood.
Reference: https://docs.python.org/3/library/functools.html#functools.total_ordering

2023-08-28 02:18 UTC, ivanovmg commented on unitsnet_py/abstract_unit.py
> +            return NotImplemented
This is what happens when we use ``return NotImplemented``: the comparison is delegated to ``other`` object.
If the ``other`` object cannot perform the comparison as well, then ``TypeError`` is raised.
This is common in Python to implement comparisons this way.

References:
- https://stackoverflow.com/questions/1062096/python-notimplemented-constant
- https://docs.python.org/3.6/library/constants.html#NotImplemented

2023-08-28 06:02 UTC, haimkastner approved these changes

2023-08-28 06:03 UTC, merged

2023-08-28 06:08 UTC, haimkastner commented
Merged, thank you for your contribution 🙏